cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.event_list, name='calendar'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
]

people/urls.py
from django.urls import path

from . import views

app_name = 'people'
urlpatterns = [
    # path('', views.index, name='index'),
    path('<slug:slug>/', views.person_detail, name='person'),
]

tutorials/urls.py
from django.urls import path, re_path

from . import views

app_name = 'tutorials'
urlpatterns = [
    path('', views.module_list, name='modules'),
    path('series/', views.serieses, name='serieses'),
    path('module/<slug:slug>/', views.module, name='module'),
    path('serieses/<int:series_id>/', views.series, name='series')
]

vialab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import markdown_uploader

urlpatterns = [
    path('classes/', include('classes.urls')),
    path('calendar/', include('cal.urls')),
    path('reading/', include('reading.urls')),
    path('people/', include('people.urls')),
    path('tutorials/', include('tutorials.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # Necessary for Martor.
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name="markdown_uploader_page"),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.functional import cached_property
from django.urls import reverse
from martor.models import MartorField
from autoslug import AutoSlugField
from autoslug.settings import slugify
from simple_history.models import HistoricalRecords
import os
import time

def photo_filename(instance, filename):
    path = 'images/personphotos'
    fname, fext = os.path.splitext(filename)
    f = '{0}-{1}'.format(instance.last, instance.first).replace(' ', '-').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, f)

class PeopleMetadata(models.Model):
    name = models.CharField(max_length=25)
    desc = MartorField(max_length=1000, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        verbose_name = "people app metadata"
        verbose_name_plural = "people app metadata"

    def __str__(self):
        return self.name

class Institution(models.Model):
    name = models.CharField(
        help_text="Name of the institution.",
        max_length=150, 
        blank=True, 
        null=True
    )
    short = models.CharField(
        max_length=150, 
        blank=True, 
        null=True
    )
    abbr = models.CharField(
        max_length=10, 
        blank=True, 
        null=True
    )
    room = models.CharField(
        help_text = "Room at which the institution can be reached.",
        max_length=20, 
        null=False, 
        blank=True, 
        default=''
    )
    address = models.CharField(
        help_text = "Address of the institution.",
        max_length=200, 
        null=False, 
        blank=True, 
        default=''
    )
    city = models.CharField(
        help_text = "City in which institution is located.",
        max_length=100
    )
    state = models.CharField(
        help_text = "State in which institution is located.",
        max_length=100
    )
    postal = models.CharField(
        help_text = "Postcode in which institution is located.",
        max_length=20,
        blank=True,
        default=''
    )
    country = models.CharField(
        help_text = "Country in which institution is located.",
        max_length=100
    )
    website = models.URLField(
        help_text = "Institution's website.",
        null=False, 
        blank=True, 
        default=''
    )
    parent = models.ForeignKey(
        'self', 
        help_text = "Parent institution of institution (E.g., 'MIT' is the parent of 'DUSP').",
        null=True, 
        blank=True, 
        on_delete=models.SET_NULL
    )
    history = HistoricalRecords()
    # location = models.PointField(
    #     help_text = "Approximate location of institution.",
    #     null=True,
    #     blank=True
    # )

    # def save(self, *args, **kwargs):
    #     """
    #     Overwrite save method to update main bibliography when model is saved.
    #     """
    #     if self.location:
    #         pass
    #     else:
    #         add_array = [self.address, self.city, self.state, self.postal, self.country]
    #         query = ','.join(filter(None, add_array))
    #         self.location = geocode_address(query)
    #     super(Institution, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "institution"
        verbose_name_plural = "institutions"

    def __str__(self):
        return str(self.name)

class Person(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to = photo_filename)
    first = models.CharField(max_length=25)
    middle = models.CharField(max_length=25, blank=True, default='')
    last = models.CharField(max_length=25)
    CREDS = [
        ('MCP', 'Master of City Planning'),
        ('PhD', 'Doctor of Philosophy'),
        ('MUP', 'Master of Urban Planning'),
        ('MURP', 'Master of Urban and Regional Planning'),
        ('MFA', 'Master of Fine Arts'),
        ('MLA', 'Master of Landscape Architecture'),
        ('MArch', 'Master of Architecture'),
        ('MBA', 'Master of Business Administration'),
        ('MPA', 'Master of Public Administration'),
        ('MDes', 'Master of Design Studies'),
        ('DDes', 'Doctor of Design'),
    ]
    cred = models.CharField(
        max_length = 5,
        choices = CREDS,
        default = 'PhD',
        null=True,
        blank=True
    )
    affil = models.ManyToManyField(
        Institution, 
        through='Affiliation'
    )
    email = models.EmailField(blank=True, default='')
    website = models.URLField(blank=True, default='')
    GENDERS = [
        ('M', 'He/him'),
        ('W', 'She/her'),
        ('N', 'He/him or They/them'),
        ('H', 'She/her or They/them'),
        ('T', 'They/them'),
    ]
    pronouns = models.CharField(
        max_length=1,
        choices=GENDERS,
        default='T',
    )
    bio = MartorField(
        max_length=3000, 
        blank=True
    )
    orcid = models.CharField(
        max_length=19, 
        blank=True, 
        default=''
    )
    pgp = models.CharField(
        max_length=50, 
        blank=True, 
        default=''
    )
    twitter = models.CharField(
        max_length=50, 
        blank=True, 
        default=''
    )
    gitlab = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    github = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    zotero = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    linkedin = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    django_user = models.ForeignKey(
        User, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(auto_now=True)
    vita = models.FileField(
        upload_to='people/vitae/', 
        blank=True, 
        default=''
    )
    slug = models.SlugField(
        default='',
        editable=False,
        unique=True
    )
    page = models.BooleanField(
        default=False
    )
    history = HistoricalRecords()

    @property
    def link(self):
        """
        Returns url for links.
        Application page if 'page' attribute is true.
        Else webpage.
        Else Twitter.
        Else nothing.
        """
        if self.page:
            return reverse('people:person', args=[self.slug])
        elif self.website:
            return self.website
        elif self.twitter:
            return "https://twitter.com/" + self.twitter


    @property
    def full_name(self):
        """
        Returns full name.
        """
        return '%s %s %s' % (self.first, self.middle, self.last)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(self.first),
                slugify(self.middle),
                slugify(self.last),
            ))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "person"
        verbose_name_plural = "people"

    def __str__(self):
        return self.full_name

class Affiliation(models.Model):
    participant = models.ForeignKey(
        Person, 
        on_delete=models.CASCADE, 
        related_name="affiliation"
    )
    institution = models.ForeignKey(
        Institution, 
        on_delete = models.CASCADE, 
        related_name = "affiliation"
    )
    primary = models.BooleanField(
        default=False
    )
    website = models.URLField(
        default='', 
        blank=True
    )
    title = models.CharField(
        max_length=150
    )
    desc = models.CharField(
        max_length=450,
        default = '',
        blank = True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return self.title

tutorials/models.py
from django.db import models
from martor.models import MartorField
from django.db.models import Prefetch
from people.models import Person
from reading.models import ReadingList
from main.models import MainMetadata
from main.pandoc import pandocify
from django.utils.functional import cached_property
import time
import os

def banner_filename(instance, filename):
    path = 'images/banners/'
    fname, fext = os.path.splitext(filename)
    format = instance.title.replace(' ', '-').replace('.', '').replace(',','').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, format)

def icon_filename(instance, filename):
    path = 'images/icons'
    fname, fext = os.path.splitext(filename)
    format = instance.name.replace(' ', '-').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, format)

class TutorialsMetadata(models.Model):
    app_name = models.CharField(max_length=25)
    app_desc = MartorField(max_length=1000, blank=True)
    modules_name = models.CharField(max_length=25)
    modules_desc = MartorField(max_length=1000, blank=True)
    series_name = models.CharField(max_length=25)
    series_desc = MartorField(max_length=1000, blank=True)
    episode_name = models.CharField(max_length=15, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "tutorials metadata"
        verbose_name_plural = "tutorials metadata"

    def __str__(self):
        return self.app_name

class Series(models.Model):
    title = models.CharField(max_length=100)
    desc = MartorField(max_length=2000, blank=True)
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    featured = models.BooleanField(default=False)
    published = models.BooleanField(default=False)

    @property
    def author_list(self):
        modules = Module.objects.filter(series = self.pk)
        return Person.objects.filter(module__id__in = modules.values_list('id', flat=True)).distinct().order_by('last')

    @property
    def episode_list(self):
        return Module.objects.filter(series = self.pk).distinct().order_by('episode__number')

    @property
    def software_list(self):
        modules = Module.objects.filter(series = self.pk)
        return Software.objects.filter(module__id__in = modules.values_list('id', flat=True)).distinct().order_by('name')
    
    @property
    def skill_list(self):
        modules = Module.objects.filter(series = self.pk)
        return Skill.objects.filter(module__id__in = modules.values_list('id', flat=True)).distinct().order_by('name')
    
    @property
    def created(self):
        return self.history.earliest()

    @property
    def creator(self):
        return Person.objects.all().get(django_user=self.history.earliest().history_user)
    
    @property
    def modified(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return self.history.latest()

    @property
    def modifier(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return Person.objects.all().get(django_user=self.history.latest().history_user)

    class Meta:
        verbose_name = "series"
        verbose_name_plural = "series"

    def __str__(self):
        return self.title
    
class Software(models.Model):
    name = models.CharField(max_length=100)
    desc = MartorField(max_length=400)
    icon = models.ImageField(null=True, blank=True, upload_to = icon_filename)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "software"
        verbose_name_plural = "software"

    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length=100)
    desc = MartorField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "skill"
        verbose_name_plural = "skills"

    def __str__(self):
        return self.name

class Module(models.Model):
    title = models.CharField(max_length=100)
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    author = models.ManyToManyField(Person)
    software = models.ManyToManyField(Software, blank=True)
    skills = models.ManyToManyField(
        Skill, 
        blank=True
    )
    series = models.ManyToManyField(Series, through='Episode', blank=True)
    desc = MartorField(max_length=1000, blank=True)
    body = MartorField(blank=True, default='')
    whatnext = MartorField(blank=True, default='')
    readings = models.ForeignKey(
        ReadingList, 
        null=True, 
        blank=True, 
        on_delete=models.SET_NULL
    )
    materials = models.FileField(upload_to='uploads/%Y/%m/%d', blank=True, default='')
    published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    featured = models.BooleanField()
    slug = models.SlugField(
        default='',
        editable=True,
        unique=False
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(self.title),
            ))
        super().save(*args, **kwargs)

    @property
    def author_list(self):
        return Person.objects.filter(module__id=self.id)
    
    @property
    def software_list(self):
        return Software.objects.filter(module__id=self.id)
    
    @property
    def skill_list(self):
        return Skill.objects.filter(module__id=self.id)
    
    @property
    def created(self):
        return self.history.earliest()

    @property
    def creator(self):
        return Person.objects.all().get(django_user=self.history.earliest().history_user)
    
    @property
    def modified(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return self.history.latest()

    @property
    def modifier(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return Person.objects.all().get(django_user=self.history.latest().history_user)

    @cached_property
    def pandoc_process(self):
        main = MainMetadata.objects.latest('id')
        print(main)
        try:
            biblio=main.bib.url
            print(biblio)
            cite=main.csl.url
        except:
            biblio=None
            cite=None
        return pandocify(
            content=self.body,
            csl=cite,
            bib=biblio
        )

    class Meta:
        verbose_name = "module"
        verbose_name_plural = "modules"

    def __str__(self):
        return self.title

class Episode(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    number = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "episode"
        verbose_name_plural = "episodes"

    def __str__(self):
        return self.module.title + self.series.title + str(self.number)

tutorials/forms.py
from django import forms
from martor.fields import MartorFormField

class PostForm(forms.Form):
    description = MartorFormField()

tutorials/templates/tutorials/module_detail.html
{% extends "main/base.html" %}
{% load static %}
{% load martortags %}
{% block content %}

{% if module %}
{% if module.banner %}
<div class="hero" style="background-image: url({{module.banner.url}});">
{% else %}
<div class="hero" style="box-shadow:none;">
{% endif %}
  <div class="long-title card gradient">
    <div class="card-segment">
        <h1 id="title">{{ module.title }}</h1>
        <hr>
        <div class="instructors">
        {% for a in module.author.all %}
        {% if a.photo %}
        <div class="instructor-xs-photo">
            <a href="{% url 'people:person' a.slug %}"><img src="{{ a.photo.url }}"/></a>
        </div>{% endif %}<div class="instructor-info">
            <ul>
                {% if a.full_name %}<li><h3><a href="{% url 'people:person' a.slug %}">{{ a.full_name }}{% if a.cred == 'PhD' %}, {{a.cred}} {% endif %}{% endif %}
                {% if a.pronouns %}({{ a.get_pronouns_display }}){% else %}{% endif %}</li></a></h3>
                {% if a.affiliation.first.title %}<li>{{ a.affiliation.first.title }}</li>{% endif %}
                {% if a.email %}<li><a href="mailto:{{ a.email }}">{{ a.email }}</a>{% endif %}
            </ul>
        </div>
        {% endfor %}
        </div>
    </div>
  </div>
</div>
<div class="card-array"> 
  <div class="sidebyside card hawt">
      <div class="card-segment">
          <h2 class="card-segment-head">
              Tutorial Information
          </h2>
          <hr>
          <div class="card-segment-body">
              {% if module.series.all %}
                  <ul class="list-unstyled">
                  {% for s in module.episode_set.all %}
                    <li>Module {{s.number}} in {{s.series.title}}.</li>
                  {% endfor %}
                  </ul>
              {% endif %}
          </div>
          <div class="card-button-list">
              <ul>
                  {% if module.materials %}
                  <a href="{{ module.materials.url }}"><li class="gradient">Download Materials ></li></a>
                  {% endif %}
              </ul>
          </div>
      </div>
  </div><div class="sidebyside card hawt">
    {% if module.skills.all %}
      <div class="card-segment">
          <h2 class="card-segment-head">
              Methods
          </h2>
          <hr>
          <div class="card-segment-body">
                  {% for s in module.skills.all %}
                      {{ s.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
             
          </div>
        </div>
        {% endif %}
        {% if module.software.all %}
        <div class="card-segment">
          <h2 class="card-segment-head">
              Tools
          </h2>
          <hr>
          <div class="card-segment-body">
              {% for s in module.software.all %}
                  {{ s.name }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
          </div>
      </div>
      {% endif %}
  </div>
</div>
<div class="row section">
  <div class="long-content">
  {{module.pandoc_process|safe_markdown}}
  </div>
</div>
{% endif %}
{% endblock %}

{% block js %}
{% comment %} Read in Martor parser. {% endcomment %}
<script src="{% static 'moduleParse.bundle.js' %}"></script>
{% endblock %}

tutorials/templates/tutorials/module_list.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="feature-text"><p>Tutorials</p></div>
    <div class="selectors"> 
        <form method="get" onchange="this.submit()">
            <div class="card-array"> 
                <div class="selector card">
                    <div class="card-segment">{{ modules.form.software }}</div>
                </div>
                <div class="selector card">
                    <div class="card-segment">{{ modules.form.skills }}</div>
                </div>
            </div>
        </form>
    </div>
    {% if modules.qs %}
    <div class="card-array"> 
        {% include page_template %}
    </div>
{% else %}
<div class="long-content">
    No matching tutorials.
</div>
{% endif %}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js'%}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 200
        });
    </script>
{% endblock %}

tutorials/templates/tutorials/module_list_page.html
{% load el_pagination_tags %}
{% load martortags %}



{% paginate modules.qs as modules %}
{% for m in modules %}<div class="card {% if m.cancel %}cancel{% endif %}">
<div class="card-segment">
    {% if m.banner %}
        <a href="{% url 'tutorials:module' m.slug %}"><div class="card-img"><div style="background-image:url({{m.banner.url}})"></div></div></a>
    {% endif %}
    <h2 class="card-segment-head"><a href="{% url 'tutorials:module' m.slug %}">{{m.title}}</a></h2>
    {% if m.software %}
        {% for soft in m.software.all %} <code>{{soft.name}}</code> {% endfor %}
    {% endif %} | {% if m.skills %}
        {% for skill in m.skills.all %} <code>{{skill.name}}</code> {% endfor %}
    {% endif %}
    <hr>
    {% for a in m.author.all %}
        <h4><a href="{% url 'people:person' a.slug %}">{{a.full_name}}</a></h4>
    {% endfor %}
    {% if m.desc %}
        {{ m.desc|safe_markdown|truncatewords:15 }}
    {% elif m.body %}
        {{ m.body|safe_markdown|truncatewords:15 }}
    {% endif %}
</div>
</div>{% endfor %}
{% show_more %}

tutorials/templates/tutorials/series.html
{% extends "main/base.html" %}
{% load martortags %}
{% block content %}

<div class="container">
<div class="row section">
  <div class="col-12">
    <div class="jumbotron" style="background-image: url({{series.banner.url}});background-size:cover;">
      <div class="jumbo-text">
        <h1 class="display-4">{{series.title}}</h1>
        <h6 class="card-subtitle mb-2 text-muted">
        {% comment %} {% for a in series.author_list.all %}
            <a href="{% url 'people:person' a.id %}">{{ a.full_name }}</a>
        {% endfor %} {% endcomment %}
        </h6>
        <p class="lead">{{series.desc|safe_markdown}}</p>
        <hr class="my-4">
        <ul class="skillsoft">
          <li>Skills: {% for sk in series.skill_list.all %}
              <a href="#">{{sk}}</a>
          {% endfor %}</li>
          <li>Software: {% for so in series.software_list.all %}
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="{{so.desc}}">{{so}}</a>
          {% endfor %}</li>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <div class="row section">
    <div class="col-12">
      {% for episode in series.episode_list %}
        <div class="card card-left mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img class="card-img" src="{{episode.banner.url}}" alt="Card image cap">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"><code>{{tutorials_meta.episode_name}} {{episode.episode_set.all.first.number}}</code></h6>
                <h5 class="card-title"><a href="{% url 'tutorials:module' episode.id %}">{{episode.title}}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">
                {% for a in episode.author_list.all %}
                    <a href="{% url 'people:person' a.id %}">{{ a.full_name }}</a>
                {% endfor %}
                </h6>
                <hr>
                <p class="card-text">{{episode.desc|safe_markdown|truncatewords:12}}</p>
                <hr>
                <ul class="skillsoft">
                  <li>Skills: {% for sk in episode.skill_list.all %}
                      <a href="#">{{sk}}</a>
                  {% endfor %}</li>
                  <li>Software: {% for so in episode.software_list.all %}
                      <a href="#" data-toggle="tooltip" data-placement="bottom" title="{{so.desc}}">{{so}}</a>
                  {% endfor %}</li>
                  {% if episode.readings %}
                  <li><a href="{% url 'reading:reading_list' episode.readings.id %}">Reading List</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

{% block sidebar %}

{% for author in series.author_list.all %}
  <img class="author-photo" src="{{ author.photo.url }}"/><br>
  <ul class="list-unstyled">
    <li><a href="{% url 'people:person' author.id %}">{{ author.full_name }}</a></li>
    <li><code><a href="mailto:{{ author.email }}">{{ author.email }}</a></code></li>
    <li>{{ author.get_pronouns_display }}.<a href="https://uwm.edu/lgbtrc/support/gender-pronouns/">*</a></li>
    <hr>
    <li>{{ author.bio|safe_markdown|truncatewords:12 }}</li>
  </ul>
  {% endfor %}

{% endblock %}

tutorials/templates/tutorials/serieses.html
{% extends "main/base.html" %}

{% load martortags %}

{% block content %}

<div class="container">
    <div class="row section">
        <div class="col-12">
            <div class="jumbotron" style="background-image: url({{featured.banner.url}});background-size:cover;">
                <div class="jumbo-text">
                    <h6 class="card-subtitle mb-2 text-muted"><code>Featured</code></h6>
                    <h1 class="display-4"><a href="{% url 'tutorials:series' featured.id %}">{{featured.title}}</a></h1>
                    <h6 class="card-subtitle mb-2 text-muted">
                    {% for a in featured.author_list.all %}
                        <a href="{% url 'people:person' a.id %}">{{ a.full_name }}</a>
                    {% endfor %}
                    </h6>
                    <p class="lead">{{featured.desc|safe_markdown}}</p>
                    <hr></hr>
                    <div class="row">
                    {% for e in featured.episode_list.all %}
                        <div class="col-md-6 episode-list"><code>Episode {{forloop.counter}}: <a href="{% url 'tutorials:module' e.id %}">{{e}}</code></a></div>
                    {% endfor %}
                    </div>
                    <hr></hr>
                    <ul class="skillsoft">
                        <li>Skills: {% for sk in featured.skill_list.all %}
                            <a href="#">{{sk}}</a>
                        {% endfor %}</li>
                        <li>Software: {% for so in featured.software_list.all %}
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="{{so.desc}}">{{so}}</a>
                        {% endfor %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row section">
        <div class="col-12">
            <h1>{% if tutorials_meta.series_name %}{{tutorials_meta.series_name}}{% else %}Series{% endif %}</h1>
            <p>{% if tutorials_meta.series_desc %}{{tutorials_meta.series_desc|safe_markdown}}{% else %}A description of the series.{% endif %}</p>
            <form method="get">
                {{serieses.form.as_table}}
                <input type ="submit"/>
            </form>
            <hr></hr>
        </div>
    </div>
    <div class="row section">
        <div class="col-12">
            {% if serieses.qs %}
                {% for s in serieses.qs %}
                <div class="card card-left mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img class="card-img-top" src="{{s.banner.url}}" alt="Card image cap">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{% url 'tutorials:series' s.id%}">{{s.title}}</a></h5>
                                <h6 class="card-subtitle mb-2 text-muted">
                                {% for a in s.author_list.all %}
                                    <a href="{% url 'people:person' a.id %}">{{ a.full_name }}</a>
                                {% endfor %}
                                <hr>
                                <p>{{s.desc|safe_markdown|truncatewords:15}}</p>
                                {% for e in s.episode_list.all %}
                                    <span class="episode-list"><code>Episode {{forloop.counter}}: <a href="{% url 'tutorials:module' e.id %}">{{e}}</code></a></span>
                                {% endfor %}
                                </h6>
                                <hr>
                                <ul class="skillsoft">
                                    <li>
                                        Skills: {% for sk in s.skill_list.all %}
                                            <a href="#">{{sk}}</a>
                                        {% endfor %}
                                    </li>
                                    <li>
                                        Software: {% for so in s.software_list.all %}
                                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="{{so.desc}}">{{so}}</a>
                                        {% endfor %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No tutorials.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}