cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.event_list, name='calendar'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
]

tutorials/urls.py
from django.urls import path, re_path

from . import views

app_name = 'tutorials'
urlpatterns = [
    path('', views.module_list, name='modules'),
    path('series/', views.serieses, name='serieses'),
    path('module/<slug:slug>/', views.module, name='module'),
    path('serieses/<int:series_id>/', views.series, name='series')
]

vialab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import markdown_uploader

urlpatterns = [
    path('classes/', include('classes.urls')),
    path('calendar/', include('cal.urls')),
    path('reading/', include('reading.urls')),
    path('people/', include('people.urls')),
    path('tutorials/', include('tutorials.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # Necessary for Martor.
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name="markdown_uploader_page"),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from martor.models import MartorField
from simple_history.models import HistoricalRecords
from autoslug.settings import slugify
from autoslug import AutoSlugField

# Import other models.
from people.models import Person, Institution
from tutorials.models import Module

import os
import time

def banner_filename(instance, filename):
    path = 'images/banners/'
    fname, fext = os.path.splitext(filename)
    format = instance.title.replace(' ', '-').replace('.', '').replace(',','').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, format)

class EventMetadata(models.Model):
    name = models.CharField(
        max_length=25
    )
    desc = MarkdownxField(
        max_length=1000, 
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()
    

    class Meta:
        verbose_name = "event app metadata"
        verbose_name_plural = "event app metadata"

    def __str__(self):
        return self.name

class Venue(models.Model):
    name = models.CharField(
        max_length=100
    )
    inst = models.ForeignKey(
        Institution, 
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()

    class Meta:
        verbose_name = "venue"
        verbose_name_plural = "venues"

    def __str__(self):
        return self.name

class Semester(models.Model):
    SEMESTERS = [
        ('S', 'Spring'),
        ('3', 'Spring (H3)'),
        ('4', 'Spring (H4)'),
        ('F', 'Fall'),
        ('1', 'Fall (H1)'),
        ('2', 'Fall (H2)'),
        ('I', 'IAP'),
        ('M', 'Summer'),
    ]
    semester = models.CharField(
        max_length=1,
        choices=SEMESTERS,
        default='T'
    )
    start = models.DateField(
        auto_now=False
    )
    end = models.DateField(
        auto_now=False
    )

    @property
    def year(self):
        return self.start.year

    def __str__(self):
        return self.get_semester_display() + ' ' + str(self.start.year)

class Event(models.Model):
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    day = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    semester = models.ForeignKey(
        Semester, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    ) 
    title = models.CharField(
        max_length=100
    )
    desc = MartorField(
        blank=True,
        null=True
    )
    participant = models.ManyToManyField(
        Person, 
        through='Role'
    )
    sponsors = models.ManyToManyField(
        Institution,
        blank = True
    )
    virtual_url = models.URLField(
        blank=True, 
        null=True
    )
    cost = models.DecimalField(
        max_digits=6, 
        decimal_places=2, 
        null=False,
        default = 0
    )
    ticket_url = models.URLField(
        blank=True, 
        null=True
    )
    venue = models.ForeignKey(
        Venue, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    module = models.ForeignKey(
        Module, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    cancel = models.BooleanField(
        default=False
    )
    published = models.BooleanField(
        default=False
    )
    featured = models.BooleanField(
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    slug = AutoSlugField(
        populate_from='title', 
        default='',
        editable=False,
        unique=True
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(str(self.day)),
                slugify(self.title)
            ))
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"

    def __str__(self):
        return self.title

class Role(models.Model):
    participant = models.ForeignKey(Person, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    ROLES = [
        ('D', 'Discussant'),
        ('M', 'Moderator'),
        ('P', 'Panelist'),
        ('L', 'Lecturer'),
        ('I', 'Introducer'),
        ('W', 'Workshop Leader')
    ]
    role = models.CharField(
        max_length=1,
        choices=ROLES,
        default='L',
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "role"
        verbose_name_plural = "roles"
    
    def __str__(self):
        return self.role

class Days(models.Model):
    order = models.SmallIntegerField()
    day = models.CharField(max_length=10)
    abbrev = models.CharField(max_length=3)

    def __str__(self):
        return self.day

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.functional import cached_property
from django.urls import reverse
from martor.models import MartorField
from autoslug import AutoSlugField
from autoslug.settings import slugify
from simple_history.models import HistoricalRecords
import os
import time

def photo_filename(instance, filename):
    path = 'images/personphotos'
    fname, fext = os.path.splitext(filename)
    f = '{0}-{1}'.format(instance.last, instance.first).replace(' ', '-').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, f)

class PeopleMetadata(models.Model):
    name = models.CharField(max_length=25)
    desc = MartorField(max_length=1000, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        verbose_name = "people app metadata"
        verbose_name_plural = "people app metadata"

    def __str__(self):
        return self.name

class Institution(models.Model):
    name = models.CharField(
        help_text="Name of the institution.",
        max_length=150, 
        blank=True, 
        null=True
    )
    short = models.CharField(
        max_length=150, 
        blank=True, 
        null=True
    )
    abbr = models.CharField(
        max_length=10, 
        blank=True, 
        null=True
    )
    room = models.CharField(
        help_text = "Room at which the institution can be reached.",
        max_length=20, 
        null=False, 
        blank=True, 
        default=''
    )
    address = models.CharField(
        help_text = "Address of the institution.",
        max_length=200, 
        null=False, 
        blank=True, 
        default=''
    )
    city = models.CharField(
        help_text = "City in which institution is located.",
        max_length=100
    )
    state = models.CharField(
        help_text = "State in which institution is located.",
        max_length=100
    )
    postal = models.CharField(
        help_text = "Postcode in which institution is located.",
        max_length=20,
        blank=True,
        default=''
    )
    country = models.CharField(
        help_text = "Country in which institution is located.",
        max_length=100
    )
    website = models.URLField(
        help_text = "Institution's website.",
        null=False, 
        blank=True, 
        default=''
    )
    parent = models.ForeignKey(
        'self', 
        help_text = "Parent institution of institution (E.g., 'MIT' is the parent of 'DUSP').",
        null=True, 
        blank=True, 
        on_delete=models.SET_NULL
    )
    history = HistoricalRecords()
    # location = models.PointField(
    #     help_text = "Approximate location of institution.",
    #     null=True,
    #     blank=True
    # )

    # def save(self, *args, **kwargs):
    #     """
    #     Overwrite save method to update main bibliography when model is saved.
    #     """
    #     if self.location:
    #         pass
    #     else:
    #         add_array = [self.address, self.city, self.state, self.postal, self.country]
    #         query = ','.join(filter(None, add_array))
    #         self.location = geocode_address(query)
    #     super(Institution, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "institution"
        verbose_name_plural = "institutions"

    def __str__(self):
        return str(self.name)

class Person(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to = photo_filename)
    first = models.CharField(max_length=25)
    middle = models.CharField(max_length=25, blank=True, default='')
    last = models.CharField(max_length=25)
    CREDS = [
        ('MCP', 'Master of City Planning'),
        ('PhD', 'Doctor of Philosophy'),
        ('MUP', 'Master of Urban Planning'),
        ('MURP', 'Master of Urban and Regional Planning'),
        ('MFA', 'Master of Fine Arts'),
        ('MLA', 'Master of Landscape Architecture'),
        ('MArch', 'Master of Architecture'),
        ('MBA', 'Master of Business Administration'),
        ('MPA', 'Master of Public Administration'),
        ('MDes', 'Master of Design Studies'),
        ('DDes', 'Doctor of Design'),
    ]
    cred = models.CharField(
        max_length = 5,
        choices = CREDS,
        default = 'PhD',
        null=True,
        blank=True
    )
    affil = models.ManyToManyField(
        Institution, 
        through='Affiliation'
    )
    email = models.EmailField(blank=True, default='')
    website = models.URLField(blank=True, default='')
    GENDERS = [
        ('M', 'He/him'),
        ('W', 'She/her'),
        ('N', 'He/him or They/them'),
        ('H', 'She/her or They/them'),
        ('T', 'They/them'),
    ]
    pronouns = models.CharField(
        max_length=1,
        choices=GENDERS,
        default='T',
    )
    bio = MartorField(
        max_length=3000, 
        blank=True
    )
    orcid = models.CharField(
        max_length=19, 
        blank=True, 
        default=''
    )
    pgp = models.CharField(
        max_length=50, 
        blank=True, 
        default=''
    )
    twitter = models.CharField(
        max_length=50, 
        blank=True, 
        default=''
    )
    gitlab = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    github = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    zotero = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    linkedin = models.CharField(
        max_length=25, 
        blank=True, 
        default=''
    )
    django_user = models.ForeignKey(
        User, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(auto_now=True)
    vita = models.FileField(
        upload_to='people/vitae/', 
        blank=True, 
        default=''
    )
    slug = models.SlugField(
        default='',
        editable=False,
        unique=True
    )
    page = models.BooleanField(
        default=False
    )
    history = HistoricalRecords()

    @property
    def link(self):
        """
        Returns url for links.
        Application page if 'page' attribute is true.
        Else webpage.
        Else Twitter.
        Else nothing.
        """
        if self.page:
            return reverse('people:person', args=[self.slug])
        elif self.website:
            return self.website
        elif self.twitter:
            return "https://twitter.com/" + self.twitter


    @property
    def full_name(self):
        """
        Returns full name.
        """
        return '%s %s %s' % (self.first, self.middle, self.last)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(self.first),
                slugify(self.middle),
                slugify(self.last),
            ))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "person"
        verbose_name_plural = "people"

    def __str__(self):
        return self.full_name

class Affiliation(models.Model):
    participant = models.ForeignKey(
        Person, 
        on_delete=models.CASCADE, 
        related_name="affiliation"
    )
    institution = models.ForeignKey(
        Institution, 
        on_delete = models.CASCADE, 
        related_name = "affiliation"
    )
    primary = models.BooleanField(
        default=False
    )
    website = models.URLField(
        default='', 
        blank=True
    )
    title = models.CharField(
        max_length=150
    )
    desc = models.CharField(
        max_length=450,
        default = '',
        blank = True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()

    def __str__(self):
        return self.title

cal/views.py
from django.shortcuts import get_object_or_404, render
from datetime import date
from django.views import generic
from el_pagination.views import AjaxListView
from datetime import date, timedelta, datetime
from .models import Event

def event_list(request,
    template='cal/event_list.html',
    page_template='cal/event_list_page.html'):
    context = {
        'current_upcoming': Event.objects.filter(
            day__gte=date.today()
        ).prefetch_related(
            'participant'
        ).select_related(
            'venue'
        ).select_related(
            'module'
        ).order_by('day'),
        'page_template': page_template,
    }
    if request.is_ajax():
        template = page_template
    return render(request, template, context)

# class EventListView(AjaxListView):
#     """
#     Event list view, which splits events into current/upcoming
#     and past. The latter is paginated using el-pagination.
#     """
#     context_object_name = 'event_list'
#     template_name = 'cal/event_list.html'
#     page_template = 'cal/event_list_list_page.html'

#     def get_queryset(self):
#         """
#         Get archived events (prior to current day).
#         """
#         return Event.objects.filter(
#             day__lt=date.today()
#         ).prefetch_related(
#             'participant'
#         ).prefetch_related(
#             'topics'
#         ).select_related(
#             'venue'
#         ).select_related(
#             'module'
#         ).order_by('day')

#     def get_context_data(self, **kwargs):
#         context = super(EventListView, self).get_context_data(**kwargs)
#         """
#         Get current and upcoming events.
#         """
#         context['current_upcoming'] = Event.objects.filter(
#             day__gte=date.today()
#         ).prefetch_related(
#             'participant'
#         ).prefetch_related(
#             'topics'
#         ).select_related(
#             'venue'
#         ).select_related(
#             'module'
#         ).order_by('day')
#         return context

class EventDetailView(generic.DetailView):
    model = Event
    template_name = 'cal/event_detail.html'
    context_object_name = 'event_detail'

cal/templates/cal/event_detail.html
{% extends "main/base.html" %}
{% load martortags %}

{% block content %}
{% if event_detail.banner %}
    <div class="hero" style="background-image: url({{event_detail.banner.url}});">
{% elif event_detail.module.banner %}
    <div class="hero" style="background-image: url({{event_detail.module.banner.url}});">
{% else %}
    <div class="hero" style="box-shadow:none;">
{% endif %}
    <div class="long-title card gradient">
        <div class="card-segment">
            <div id="supertitle">
                {{ event_detail.semester }}
            </div>
            <h1 id="title">{{ event_detail.title }}</h1>
            <hr>
            <div class="instructors">
                {% for i in event_detail.role_set.all %}<div class="instructor">
                    <div class="instructor-xs-photo">
                        {% if i.participant.photo %}
                            <a href="{{ i.participant.link }}"><img src="{{ i.participant.photo.url }}"/></a>
                        {% endif %}
                    </div><div class="instructor-info">
                        <ul>
                            {% if i.participant.full_name %}<li><h3><a href="{{ i.participant.link }}">{{ i.participant.full_name }}{% if i.participant.cred == 'PhD' %}, {{i.participant.cred}} {% endif %}{% endif %}
                            {% if i.participant.pronouns %}({{ i.participant.get_pronouns_display }}){% else %}{% endif %}</li></a></h3>
                            {% for a in i.participant.affiliation.all %}
                                {% if a.title %}
                                    <li>{{ a.title }}, <a href="{{ a.institution.website }}">{{ a.institution.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if i.participant.email %}<li><a href="mailto:{{ i.participant.email }}">{{ i.participant.email }}</a>{% endif %}
                        </ul>
                    </div>
                </div>{% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="card-array"> 
    <div class="sidebyside card hawt">
        <div class="card-segment">
            <h2 class="card-segment-head">
                Event Information
            </h2>
            <hr>
            <div class="card-segment-body">
                {% if event_detail.day %}
                    <h4>{{event_detail.day | date:"D M j" }}{% if event_detail.start %}, {{event_detail.start | time:"g:i"}}{% if event_detail.end %}–{{event_detail.end | time:"g:i"}}{% endif %}{% endif %}</h4>
                {% endif %}
                <div class="card-button-list">
                    <ul>
                        {% if event_detail.module %}<br>
                        <a href="{% url 'tutorials:module' event_detail.module.slug %}"><li class="gradient">View Module ></li></a>
                        {% endif %}
                        {% if event_detail.virtual_url %}
                        <a href="{{ event_detail.virtual_url }}"><li class="gradient">Join Virtual Event ></li></a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div><div class="sidebyside card hawt">
        {% if event_detail.sponsors.all %}
            <div class="card-segment">
                    <h2 class="card-segment-head">
                        Sponsors
                    </h2>
                    <hr>
                    <div class="card-segment-body">
                        {% if event_detail.sponsors.all %}
                            {% for s in event_detail.sponsors.all %}
                                <a href="{{s.website}}">{{ s.name }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
            </div>
        {% endif %}
        {% if event_detail.topics.all %}
            <div class="card-segment">
                <h2 class="card-segment-head">
                    Keywords
                </h2>
                <hr>
                <div class="card-segment-body">
                    {% if event_detail.topics.all %}
                        {% for s in event_detail.topics.all %}
                            {{ s.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
        {% if event_detail.module.skills.all %}
            <div class = "card-segment">
                <h2 class="card-segment-head">
                    Tools
                </h2>
                <hr>
                <div class="card-segment-body">
                    {% if event_detail.module.skills %}
                        {% for s in event_detail.module.skills.all %}
                            {{ s.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
        {% if event_detail.module.software %}
            <div class="card-segment">
                <h2 class="card-segment-head">
                    Software
                </h2>
                <hr>
                <div class="card-segment-body">
                    {% if event_detail.module.software %}
                        {% for s in event_detail.module.software.all %}{% if not forloop.last %}, {% endif %}
                            {{ s.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% if event_detail.desc %}
<div class="long-content">
    {{ event_detail.desc|safe_markdown }}
    <hr>
</div>
{% endif %}
{% endblock %}

cal/templates/cal/event_list.html
{% extends "main/base.html" %}
{% load martortags %}
{% load static %}

{% block content %}
<div class="feature-text"><p>Upcoming Events</p></div>
<div class="card-array"> 
    {% for e in current_upcoming %}<div class="card {% if e.cancel %}cancel{% endif %}">
    <div class="card-segment">
        {% if e.banner %}
            <a href="{% url 'cal:event_detail' e.slug %}"><div class="card-img"><div style="background-image:url({{e.banner.url}})"></div></div></a>
        {% elif e.module.banner.url %}
            <a href="{% url 'cal:event_detail' e.slug %}"><div class="card-img"><div style="background-image:url({{e.module.banner.url}})"></div></div></a>
        {% endif %}
        <h2 class="card-segment-head"><a href="{% url 'cal:event_detail' e.slug %}">{{e.title}}</a></h2>
        {% if e.day %}
            <h4>
            {{e.day | date:"D M j" }}{% if e.start %}, {{e.start | time:"g:i"}}{% if e.end %}–{{e.end | time:"g:i"}}{% endif %}{% endif %}
            </h4>
        {% endif %}
        <hr>
        <div class="card-segment-body">
        <p>{% for p in e.participant.all %}
            <a href="{{p.link}}">{{p.full_name}} ({{p.get_pronouns_display}})</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}</p>
        <p>Sponsored by {% for s in e.sponsors.all %}
            <a href="{{s.website}}">{{s.name}}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}</p>
        {{ e.desc|truncatewords:30|safe_markdown }}
            <div class="card-button-list">
                <ul>
                    {% if e.module %}
                        <li class="gradient"><a href="{% url 'tutorials:module' e.module.slug %}">Tutorial ></a></li>
                    {% endif %}
                    {% if e.virtual_url %}
                        <li class="gradient"><a href="{{ e.virtual_url }}">Zoom ></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>{% endfor %}
</div>
{% comment %} {% if event_list %}
<div class="feature-text"><p>Previous Events</p></div>
<div class="card-array">
    {% for e in event_list %}<div class="sidebyside card hawt {% if e.cancel %}cancel{% endif %}">
        <div class="card-segment">
            {% if e.banner %}
                <a href="{% url 'cal:event_detail' e.slug %}"><div class="card-img"><div style="background-image:url({{e.banner.url}})"></div></div></a>
            {% elif e.module.banner.url %}
                <a href="{% url 'cal:event_detail' e.slug %}"><div class="card-img"><div style="background-image:url({{e.module.banner.url}})"></div></div></a>
            {% endif %}
            <h2 class="card-segment-head"><a href="{% url 'cal:event_detail' e.slug %}">{{e.title}}</a></h2>
            {% if e.day %}
                <h4>
                {{e.day | date:"D M j" }}{% if e.start %}, {{e.start | time:"g:i"}}{% if e.end %}–{{e.end | time:"g:i"}}{% endif %}{% endif %}
                </h4>
            {% endif %}
            <hr>
            <div class="card-segment-body">
            {{ e.desc|truncatewords:30|safe_markdown }}
                <div class="card-button-list">
                    <ul>
                        {% if e.module %}
                            <a href="{{ e.module }}"><li>Tutorial ></li></a>
                        {% endif %}
                        {% if e.virtual_url %}
                            <a href="{{ e.virtual_url }}"><li>Zoom ></li></a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>{% endfor %}
</div>
{% endif %} {% endcomment %}
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js'%}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 200
        });
    </script>
{% endblock %}

cal/templates/cal/event_list_page.html
{% load el_pagination_tags %}
{% load martortags %}

{% paginate current_upcoming %}

{% show_more %}