cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.event_list, name='calendar'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
]

classes/urls.py
from django.urls import path

from . import views

app_name = 'classes'
urlpatterns = [
    path('', views.ClassesListView.as_view(), name='classes'),
    path('instance/<slug:slug>/', views.class_instance_detail, name='class_instance'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('colophon/', views.colophon, name='colophon'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.landing, name='landing')
]

reading/urls.py
from django.urls import path

from . import views

app_name = 'reading'
urlpatterns = [
    path('', views.reading_lists, name='reading_lists'),
    path('<slug:slug>/', views.reading_list_detail, name='reading_list_detail'),
]

tutorials/urls.py
from django.urls import path, re_path

from . import views

app_name = 'tutorials'
urlpatterns = [
    path('', views.module_list, name='modules'),
    path('series/', views.serieses, name='serieses'),
    path('module/<slug:slug>/', views.module, name='module'),
    path('serieses/<int:series_id>/', views.series, name='series')
]

vialab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import markdown_uploader

urlpatterns = [
    path('classes/', include('classes.urls')),
    path('calendar/', include('cal.urls')),
    path('reading/', include('reading.urls')),
    path('people/', include('people.urls')),
    path('tutorials/', include('tutorials.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # Necessary for Martor.
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name="markdown_uploader_page"),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from martor.models import MartorField
from simple_history.models import HistoricalRecords
from autoslug.settings import slugify
from autoslug import AutoSlugField

# Import other models.
from people.models import Person, Institution
from tutorials.models import Module

import os
import time

def banner_filename(instance, filename):
    path = 'images/banners/'
    fname, fext = os.path.splitext(filename)
    format = instance.title.replace(' ', '-').replace('.', '').replace(',','').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, format)

class EventMetadata(models.Model):
    name = models.CharField(
        max_length=25
    )
    desc = MarkdownxField(
        max_length=1000, 
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()
    

    class Meta:
        verbose_name = "event app metadata"
        verbose_name_plural = "event app metadata"

    def __str__(self):
        return self.name

class Venue(models.Model):
    name = models.CharField(
        max_length=100
    )
    inst = models.ForeignKey(
        Institution, 
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()

    class Meta:
        verbose_name = "venue"
        verbose_name_plural = "venues"

    def __str__(self):
        return self.name

class Semester(models.Model):
    SEMESTERS = [
        ('S', 'Spring'),
        ('3', 'Spring (H3)'),
        ('4', 'Spring (H4)'),
        ('F', 'Fall'),
        ('1', 'Fall (H1)'),
        ('2', 'Fall (H2)'),
        ('I', 'IAP'),
        ('M', 'Summer'),
    ]
    semester = models.CharField(
        max_length=1,
        choices=SEMESTERS,
        default='T'
    )
    start = models.DateField(
        auto_now=False
    )
    end = models.DateField(
        auto_now=False
    )

    @property
    def year(self):
        return self.start.year

    def __str__(self):
        return self.get_semester_display() + ' ' + str(self.start.year)

class Event(models.Model):
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    day = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    semester = models.ForeignKey(
        Semester, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    ) 
    title = models.CharField(
        max_length=100
    )
    desc = MartorField(
        blank=True,
        null=True
    )
    participant = models.ManyToManyField(
        Person, 
        through='Role'
    )
    sponsors = models.ManyToManyField(
        Institution,
        blank = True
    )
    virtual_url = models.URLField(
        blank=True, 
        null=True
    )
    cost = models.DecimalField(
        max_digits=6, 
        decimal_places=2, 
        null=False,
        default = 0
    )
    ticket_url = models.URLField(
        blank=True, 
        null=True
    )
    venue = models.ForeignKey(
        Venue, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    module = models.ForeignKey(
        Module, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    cancel = models.BooleanField(
        default=False
    )
    published = models.BooleanField(
        default=False
    )
    featured = models.BooleanField(
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    slug = AutoSlugField(
        populate_from='title', 
        default='',
        editable=False,
        unique=True
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(str(self.day)),
                slugify(self.title)
            ))
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"

    def __str__(self):
        return self.title

class Role(models.Model):
    participant = models.ForeignKey(Person, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    ROLES = [
        ('D', 'Discussant'),
        ('M', 'Moderator'),
        ('P', 'Panelist'),
        ('L', 'Lecturer'),
        ('I', 'Introducer'),
        ('W', 'Workshop Leader')
    ]
    role = models.CharField(
        max_length=1,
        choices=ROLES,
        default='L',
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "role"
        verbose_name_plural = "roles"
    
    def __str__(self):
        return self.role

class Days(models.Model):
    order = models.SmallIntegerField()
    day = models.CharField(max_length=10)
    abbrev = models.CharField(max_length=3)

    def __str__(self):
        return self.day

main/models.py
from django.db import models
from martor.models import MartorField
from simple_history.models import HistoricalRecords
from people.models import Person, Institution
import os
import time

def vid_filename(instance, filename):
    path = 'videos'
    fname, fext = os.path.splitext(filename)
    f = 'feature_' + str(round(time.time())) + fext
    return os.path.join(path, f)

class MainMetadata(models.Model):
    main_name = models.CharField(max_length=50, blank=False)
    short_desc = models.CharField(max_length=400, blank=False)
    about_name = models.CharField(max_length=20, blank=False)
    institution = models.ForeignKey(Institution, blank=True, null=True, on_delete=models.SET_NULL)
    about = MartorField(max_length=2000, blank=False)
    address = MartorField(max_length=2000, blank=False)
    email = models.EmailField(blank=True, default='')
    accessibility_url = models.URLField(blank=True, default='https://web.mit.edu/accessibility/')
    slack = models.URLField(max_length=50, blank=True, default='')
    twitter = models.CharField(max_length=50, blank=True, default='')
    gitlab = models.CharField(max_length=25, blank=True, default='')
    github = models.CharField(max_length=25, blank=True, default='')
    zotero = models.CharField(max_length=25, blank=True, default='')
    bib = models.FileField(upload_to='bibs/', blank=True)
    csl = models.FileField(upload_to='csls/', blank=True)
    feature_vid = models.FileField(blank=True, default='', upload_to = vid_filename)
    colophon_name = models.CharField(max_length=25, null=True, blank=True, default='')
    colophon = MartorField(max_length=12000, null=True, blank=True, default='')
    linkedin = models.CharField(max_length=25, blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    # @property
    # def about_formatted(self):
    #     return markdownify(self.about)
    
    @property
    def created(self):
        return self.history.earliest()

    @property
    def creator(self):
        return Person.objects.all().get(django_user=self.history.earliest().history_user)
    
    @property
    def modified(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return self.history.latest()

    @property
    def modifier(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return Person.objects.all().get(django_user=self.history.latest().history_user)

    class Meta:
        verbose_name = "main app metadata"
        verbose_name_plural = "main app metadata"

    def __str__(self):
        return self.main_name

main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from .models import MainMetadata
from cal.models import Event
from classes.models import ClassInstance
from cal.models import Event

from datetime import date, timedelta


# Create your views here.
def about(request):
    about = MainMetadata.objects.latest('created_at')
    return render(request, 'main/about.html', {
        'about': about,
        }
    )
def colophon(request):
    meta = MainMetadata.objects.latest('created_at')
    return render(request, 'main/colophon.html', {
        'meta': meta,
        }
    )
def contact(request):
    contact = MainMetadata.objects.latest('created_at')
    return render(request, 'main/colophon.html', {
        'contact': contact,
        }
    )

def landing(request):
    today = date.today()
    end_date = today + timedelta(weeks=20)
    print(today, end_date)
    current_upcoming = ClassInstance.objects.select_related(
            'cl__institution'
        ).select_related(
            'semester'
        ).filter(
            semester__end__range=[today, end_date]
        ).prefetch_related(
            'sessions'
        ).order_by('role', 'semester__start')
    upcoming_events = Event.objects.filter(
            day__gte=today
        ).order_by('day')[0:5]
    
    return render(request, 'main/landing.html', {
        'current_upcoming': current_upcoming,
        'upcoming_events': upcoming_events
        }
    )

main/templates/main/about.html
{% extends "main/base.html" %}
{% load martortags %}

{% block content %}
<div id="global-subtitle" class="card feature-text"><p>About</p></div>
<div class="long-content">
    {{about.about|safe_markdown}}
</div>
{% endblock %}

main/templates/main/base.html
{% load martortags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if site_data %}{{site_data.main_name}}{% else %}VIA Learning Lab{% endif %}—MIT DUSP</title>
    <!-- Add additional CSS in static file -->
    {% load static %}
    {% comment %} FontAwesome {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    {% comment %} AcademicIcons {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/academicons.min.css' %}">
    {% comment %} Load Google Fonts. {% endcomment %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    {% comment %} Custon Styles {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
</head>
<body>
    <div id="navbar">
        <div id="logo-box" class="navclass">
        <a href="{% url 'main:landing'%}">
          <span id="logo" style="display: block;">
          {% comment %} <div id="logo" class="hide-medium hawt"> {% endcomment %}
            <object id="logo-svg" type="image/svg+xml" data="{% static 'logos/vialab-logo_white.svg' %}" style="pointer-events: none;">
                Logo
            </object>
          {% comment %} </div> {% endcomment %}
          </span>
          <div class="small-hide">
          <a href="{% url 'main:landing'%}"><h3 id="global-title">{% if site_data %}{{site_data.main_name}}{% else %}VIA Learning Lab{% endif %}</h3></a>
          <h4 id="global-subtitle">Visualization, Inquiry, Analysis</h4>
          </div>
          </a>
        </div>
        <div id="nav-box" class="navclass">
          <div class="card-segment">
          <div id="toggle-nav">
            <i class="fa fa-bars fa-lg"></i>
          </div>
            <nav>
              <ul id="navlist">
                  <li><a href="{{ site_data.slack }}">Join on Slack</a></li>
                  <hr>
                  <li><a href="{% url 'cal:calendar' %}">Calendar</a></li>
                  <li><a href="{% url 'classes:classes' %}">Teaching</a></li>
                  <li><a href="{% url 'tutorials:modules' %}">Tutorials</a></li>
                  <!-- <li><a href="{% url 'reading:reading_lists' %}">Reading Lists</a></li> -->
                  <hr>
                  <li><a href="{% url 'main:about'%}" >About</a></li>
                  <li><a href="{% url 'main:colophon'%}">Colophon</a></li>
                  <hr>
                  <li><a href="{{site_data.accessibility_url}}"  target="_blank">Accessibility</a></li>
                  {% comment %} <hr class="small-hide"> {% endcomment %}
                  {% comment %} <a href="https://www.mit.edu" class="small-hide"><object type="image/svg+xml" data="{% static 'logos/mit-logo.svg' %}" class="mitlogo">
                      MIT Logo <!-- fallback image in CSS -->
                  </object></a> {% endcomment %}
              </ul>
            </nav>
            </div>
        </div>
        <div id="contact" class="hide-medium small-hide" id="title-card">
          <div class="card-segment">
            <div id="linkicons" class="hide-medium">
              {% if site_data.twitter %}
                <span class="icon"><a href="https://twitter.com/{{ site_data.twitter }}"><i class="fab fa-twitter fa-md"></i></a></span>
              {% endif %}
              {% if site_data.gitlab %}
                <span class="icon"><a href="https://gitlab.com/{{ site_data.gitlab }}"><i class="fab fa-gitlab fa-md"></i></a></span>
              {% endif %}
              {% if site_data.github %}
                <span class="icon"><a href="https://github.com/{{ site_data.github }}"><i class="fab fa-github fa-md"></i></a></span>
              {% endif %}
              {% if site_data.zotero %}
                <span class="icon"><a href="http://zotero.com/{{ site_data.zotero }}"><i class="ai ai-zotero ai-md"></i></a></span>
              {% endif %}
              {% if site_data.linkedin %}
                <span class="icon"><a href="https://linkedin.com{{site_data.linkedin}}"><i class="fab fa-linkedin fa-md"></i></a></span>
              {% endif %}
            </div>
            {% if site_data.institution %}
            <hr>
              {% if site_data.institution.dept %}<a href="{{ site_data.institution.dept_website }}"><h3>{{site_data.institution.dept}}</h3></a>{% endif %}
              {% if site_data.institution.inst %}<a href="{{ site_data.institution.inst_website }}"><h4>{{site_data.institution.inst}}</h4></a>{% endif %}
              {% if site_data.address %}
                <h4>{{ site_data.address|safe_markdown }}</h4>
              {% endif %}
              {% if site_data.email %}<a href="mailto:{{site_data.email}}"><h4><code>{{site_data.email}}</code></h4></a>{% endif %}
            {% endif %}
          </div>
        </div>
    </div>
    <div id="content-col">
      {% block content %}{% endblock %}
    </div>
    <div class="background multiply" id="video">
      <video muted="1" loop="1" autoplay="1">
        <source type="video/mp4" src="{{site_data.feature_vid.url}}">
      </video>
    </div>
    <div class="background gradient"></div>
</body>
{% block js %}{% endblock %}
<script src="{% static 'index.bundle.js' %}"></script>
</html>

main/templates/main/colophon.html
{% extends "main/base.html" %}
{% load martortags %}

{% block content %}
<div id="global-subtitle" class="card feature-text"><p>{{ site_data.colophon_name }}</p></div>
<div class="long-content">
    {{ site_data.colophon|safe_markdown }}
</div>
{% endblock %}

main/templates/main/landing.html
{% extends "main/base.html" %}
{% load martortags %}

{% block content %}
{% if site_data.short_desc %}
    <div class="feature-text">
        <p>
            {{ site_data.short_desc }}
        </p>
    </div>
{% endif %}

<div class="card-array">
    <div class="card">
        <div class="card-segment">
            <h2>Upcoming Workshops & Events</h2>
            <hr>
            {% if upcoming_events %}
                {% for event in upcoming_events%}
                <div class="list-block">
                    <h3><a href="{% url 'cal:event_detail' event.slug %}">{{event.title}}</a></h3>
                    {% if event.day %}
                        <h4>
                        {{event.day | date:"D M j" }}{% if event.start %}, {{event.start | time:"g:i"}}{% if event.end %}–{{event.end | time:"g:i"}}{% endif %}{% endif %}<br/>
                        {% for  p in event.participant.all %}
                            <a href="{{p.link}}">{{p.full_name}} ({{p.get_pronouns_display}})</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        </h4>
                    {% endif %}
                </div>
                {% endfor %}
            {% else %}
                No upcoming events.
            {% endif %}
            <hr>
            <div class="event">
                <h4><a href="{% url 'cal:calendar' %}">See all upcoming events.</a></h4>
            </div>
        </div>
    </div><div class="card">
        <div class="card-segment">
            <h2>Current Teaching</h2>
            <hr>
            {% if current_upcoming %}
                {% regroup current_upcoming by get_role_display as role_list %}
                {% for role, role_classes in role_list %}
                    <h2 class="list-block-header">{{role}}</h2>
                    {% for class in role_classes %}
                        {{class.title}}
                        <div class="list-block">
                            <!-- Class Title -->
                            {% if class.cl.title %}
                                <a href="{% url 'classes:class_instance' class.slug %}"><h3>{{class.cl.title}}</h3></a>
                            {% endif %}
                            <!-- Class Semester -->
                            {% if class.semester %}
                                <h4>
                                    {{class.semester.get_semester_display}} {{class.semester.year}} | {% if class.dept_site %}<a href="{{ class.dept_site }}">{{class.cl.institution.short}}</a>{% else %}{{class.cl.institution.short}}{% endif %}<br/>
                                    {% for  i in class.instructors.all %}
                                        <a href="{{i.link}}">{{i.full_name}} ({{i.get_pronouns_display}})</a>{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </h4>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endfor %}
            {% else %}
                No current or upcoming classes.
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}