cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.event_list, name='calendar'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
]

classes/urls.py
from django.urls import path

from . import views

app_name = 'classes'
urlpatterns = [
    path('', views.ClassesListView.as_view(), name='classes'),
    path('instance/<slug:slug>/', views.class_instance_detail, name='class_instance'),
]

people/urls.py
from django.urls import path

from . import views

app_name = 'people'
urlpatterns = [
    # path('', views.index, name='index'),
    path('<slug:slug>/', views.person_detail, name='person'),
]

vialab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import markdown_uploader

urlpatterns = [
    path('classes/', include('classes.urls')),
    path('calendar/', include('cal.urls')),
    path('reading/', include('reading.urls')),
    path('people/', include('people.urls')),
    path('tutorials/', include('tutorials.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # Necessary for Martor.
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name="markdown_uploader_page"),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from martor.models import MartorField
from simple_history.models import HistoricalRecords
from autoslug.settings import slugify
from autoslug import AutoSlugField

# Import other models.
from people.models import Person, Institution
from tutorials.models import Module

import os
import time

def banner_filename(instance, filename):
    path = 'images/banners/'
    fname, fext = os.path.splitext(filename)
    format = instance.title.replace(' ', '-').replace('.', '').replace(',','').lower() + '_' + str(round(time.time())) + fext
    return os.path.join(path, format)

class EventMetadata(models.Model):
    name = models.CharField(
        max_length=25
    )
    desc = MarkdownxField(
        max_length=1000, 
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()
    

    class Meta:
        verbose_name = "event app metadata"
        verbose_name_plural = "event app metadata"

    def __str__(self):
        return self.name

class Venue(models.Model):
    name = models.CharField(
        max_length=100
    )
    inst = models.ForeignKey(
        Institution, 
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    history = HistoricalRecords()

    class Meta:
        verbose_name = "venue"
        verbose_name_plural = "venues"

    def __str__(self):
        return self.name

class Semester(models.Model):
    SEMESTERS = [
        ('S', 'Spring'),
        ('3', 'Spring (H3)'),
        ('4', 'Spring (H4)'),
        ('F', 'Fall'),
        ('1', 'Fall (H1)'),
        ('2', 'Fall (H2)'),
        ('I', 'IAP'),
        ('M', 'Summer'),
    ]
    semester = models.CharField(
        max_length=1,
        choices=SEMESTERS,
        default='T'
    )
    start = models.DateField(
        auto_now=False
    )
    end = models.DateField(
        auto_now=False
    )

    @property
    def year(self):
        return self.start.year

    def __str__(self):
        return self.get_semester_display() + ' ' + str(self.start.year)

class Event(models.Model):
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    day = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    semester = models.ForeignKey(
        Semester, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    ) 
    title = models.CharField(
        max_length=100
    )
    desc = MartorField(
        blank=True,
        null=True
    )
    participant = models.ManyToManyField(
        Person, 
        through='Role'
    )
    sponsors = models.ManyToManyField(
        Institution,
        blank = True
    )
    virtual_url = models.URLField(
        blank=True, 
        null=True
    )
    cost = models.DecimalField(
        max_digits=6, 
        decimal_places=2, 
        null=False,
        default = 0
    )
    ticket_url = models.URLField(
        blank=True, 
        null=True
    )
    venue = models.ForeignKey(
        Venue, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    module = models.ForeignKey(
        Module, 
        blank=True, 
        null=True, 
        on_delete=models.SET_NULL
    )
    cancel = models.BooleanField(
        default=False
    )
    published = models.BooleanField(
        default=False
    )
    featured = models.BooleanField(
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )
    slug = AutoSlugField(
        populate_from='title', 
        default='',
        editable=False,
        unique=True
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(str(self.day)),
                slugify(self.title)
            ))
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"

    def __str__(self):
        return self.title

class Role(models.Model):
    participant = models.ForeignKey(Person, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    ROLES = [
        ('D', 'Discussant'),
        ('M', 'Moderator'),
        ('P', 'Panelist'),
        ('L', 'Lecturer'),
        ('I', 'Introducer'),
        ('W', 'Workshop Leader')
    ]
    role = models.CharField(
        max_length=1,
        choices=ROLES,
        default='L',
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    modified_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "role"
        verbose_name_plural = "roles"
    
    def __str__(self):
        return self.role

class Days(models.Model):
    order = models.SmallIntegerField()
    day = models.CharField(max_length=10)
    abbrev = models.CharField(max_length=3)

    def __str__(self):
        return self.day

classes/models.py
from django.db import models
from cal.models import Semester, Days
from tutorials.models import Skill, Software
from people.models import Person, Institution
from martor.models import MartorField

import os

from django.template.defaultfilters import slugify

class SessionTime(models.Model):
    days = models.ManyToManyField(Days)
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self):
        return str(list(self.days.all())) + ' ' + str(self.start) + '-' + str(self.end)

class Class(models.Model):
    title = models.CharField(max_length=100)
    number = models.CharField(max_length=15)
    ug = models.BooleanField(default=False)
    grad = models.BooleanField(default=False)
    units = models.CharField(max_length=15)
    prereqs = models.CharField(max_length=100, blank=True, null=True)
    institution = models.ForeignKey(Institution, blank=True, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    @property
    def modified(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return self.history.latest()

    @property
    def modifier(self):
        if self.history.latest().history_type == '+':
            return None
        else:
            return Person.objects.all().get(django_user=self.history.latest().history_user)

    class Meta:
        verbose_name = "class"
        verbose_name_plural = "classes"

    def __str__(self):
        return self.title

def banner_filename(instance, filename):
    path = 'images/banners/'
    fname, fext = os.path.splitext(filename)
    format = instance.slug + fext
    return os.path.join(path, format)

def syllabus_filename(instance, filename):
    path = 'syllabi/'
    _, fext = os.path.splitext(filename)
    format = instance.slug + fext
    return os.path.join(path, format)

class ClassInstance(models.Model):
    cl = models.ForeignKey(
        Class, 
        null=True, 
        on_delete=models.CASCADE, 
        related_name='instance'
    )
    semester = models.ForeignKey(
        Semester, 
        blank=True, 
        null=True, 
        on_delete=models.CASCADE
    )
    desc = MartorField(
        max_length=2000, 
        blank=True
    )
    location = models.CharField(
        max_length=200, 
        blank=True, 
        null=True
    )
    instructors = models.ManyToManyField(
        Person, 
        through='InstructorOrder'
    )
    sessions = models.ManyToManyField(
        SessionTime,
        through='SessionType', 
        blank=True
    )
    canvas = models.URLField(max_length=200)
    dept_site = models.URLField(max_length=200)
    banner = models.ImageField(null=True, blank=True, upload_to = banner_filename)
    software = models.ManyToManyField(Software, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    syllabus = models.FileField(blank=True, default='', upload_to = syllabus_filename)
    ROLE = [
        ('A', 'Teaching'),
        ('B', 'Co-Teaching'),
        ('C', 'Support'),
    ]
    role = models.CharField(max_length = 1,
        choices = ROLE,
        default = 'T'
    )
    slug = models.SlugField(
        default='',
        editable=False,
        unique=True
    )

    class Meta:
        verbose_name = "class instance"
        verbose_name_plural = "class instances"

    def __str__(self):
        return self.cl.title + ' ' + self.semester.semester + ' ' + str(self.semester.start.year)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((
                slugify(self.semester.semester),
                slugify(str(self.semester.year)),
                slugify(self.cl.title)
            ))
        super().save(*args, **kwargs)

class SessionType(models.Model):
    class_instance = models.ForeignKey(ClassInstance, null=True, on_delete=models.CASCADE, related_name='session_type')
    session_time = models.ForeignKey(SessionTime, on_delete=models.CASCADE, related_name='session_type')
    FORM = [
        ('L', 'Lecture'),
        ('B', 'Lab'),
        ('D', 'Discussion'),
        ('R', 'Recitation'),
    ]
    form = models.CharField(max_length=1,
        choices=FORM,
        default='L'
    )

    class Meta:
        verbose_name = "session"
        verbose_name_plural = "sessions"

    def __str__(self):
        return self.class_instance.cl.title + self.form

class InstructorOrder(models.Model):
    class_instance = models.ForeignKey(ClassInstance, null=True, on_delete=models.CASCADE, related_name='instructor_order')
    instructor = models.ForeignKey(Person, null=True, on_delete=models.CASCADE, related_name='instructor_order')
    order = models.SmallIntegerField(null=True)
    # def __str__(self):
        # return self.class_instance.cl.title + '/' + self.instructor

classes/forms.py
from django import forms

widgets = { 'days': forms.CheckboxSelectMultiple }

classes/views.py
from django.shortcuts import get_object_or_404, render
from classes.models import ClassInstance

from el_pagination.views import AjaxListView
from datetime import date, timedelta

class ClassesListView(AjaxListView):
    context_object_name = 'class_list'
    template_name = 'classes/class_instance_list.html'
    page_template = 'classes/class_instance_list_page.html'

    def get_queryset(self):
        """Return classes that are currently running."""
        today = date.today()
        classes = ClassInstance.objects.select_related(
            'cl__institution'
        ).select_related(
            'semester'
        ).filter(
            semester__end__lt=today
        ).prefetch_related(
            'sessions'
        ).order_by('-semester__start')
        return classes

    def get_context_data(self, **kwargs):
        today = date.today()
        context = super(ClassesListView, self).get_context_data(**kwargs)
        context['current_upcoming'] = ClassInstance.objects.select_related(
            'cl__institution'
        ).select_related(
            'semester'
        ).filter(
            semester__end__gte=today
        ).prefetch_related(
            'sessions'
        ).order_by('role', 'semester__start')
        return context

# Create your views here.
def class_instance_detail(request, slug):
    selection = ClassInstance.objects.select_related(
            'cl__institution'
        ).select_related(
            'semester'
        ).prefetch_related(
            'sessions'
        ).prefetch_related(
            'instructors'
        ).prefetch_related(
            'software'
        ).prefetch_related(
            'skills'
        ).order_by(
            'instructors__instructor_order'
        )
    class_instance = get_object_or_404(selection, slug = slug)
    return render(request, 'classes/class_instance_detail.html', {
        'class_instance': class_instance
        }
    )

classes/templates/classes/class_instance_detail.html
{% extends "main/base.html" %}
{% load static %}
{% load martortags %}
{% block content %}

{% if class_instance %}
{% if class_instance.banner %}
<div class="hero" style="background-image: url({{class_instance.banner.url}});">
{% else %}
<div class="hero" style="box-shadow:none;">
{% endif %}
    <div class="long-title card gradient">
        <div class="card-segment">
            <div id="supertitle">
                {{class_instance.cl.number }} | {{ class_instance.semester }}
            </div>
            <h1 id="title">{{ class_instance.cl.title }}</h1>
            <h4 id="subtitle">
                {% if class_instance.cl.institution %}<a href="{{ class_instance.website }}">{{class_instance.cl.institution.name}}</a> {% if class_instance.cl.institution.parent%}, <a href="{{class_instance.cl.institution.parent.website}}">{{class_instance.cl.institution.parent.name}}{% endif %}</a>{% endif %}
            </h4>
            <hr>
            <div class="instructors">
                {% for i in class_instance.instructors.all %}<div class="instructor"><div class="instructor-xs-photo">
                        {% if i.photo %}
                            <a href="{{i.link}}"><img src="{{ i.photo.url }}"/></a>
                        {% endif %}
                    </div><div class="instructor-info">
                        <ul>
                            {% if i.full_name %}<li><h3><a href="{{i.link}}">{{ i.full_name }}{% if i.cred == 'PhD' %}, {{i.cred}} {% endif %}{% endif %}
                            {% if i.pronouns %}({{ i.get_pronouns_display }}){% else %}{% endif %}</li></a></h3>
                            {% if i.affiliation.first.title %}<li>{{ i.affiliation.first.title }}</li>{% endif %}
                            {% if i.email %}<li><a href="mailto:{{ i.email }}">{{ i.email }}</a>{% endif %}
                        </ul>
                    </div>
                </div>{% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="card-array"> 
    <div class="sidebyside card hawt">
        <div class="card-segment">
            <h2 class="card-segment-head">
                Information
            </h2>
            <hr>
            <div class="card-segment-body">
                {% if class_instance.sessions %}
                {% for s in class_instance.sessions.all %}
                    {% for d in s.days.all %} 
                        {{d.abbrev}} 
                    {% endfor %}
                    {{s.start|time:"g:i"}}-{{s.end|time:"g:i"}} ({{s.session_type.first.get_form_display}})
                {% endfor %}
                {% endif %}
                <div id="eligibility"><span {% if not class_instance.cl.ug %}class="ineligible"{% endif %}>Undergrad </span> | <span {% if not class_instance.cl.grad %}class="ineligible"{% endif %}>Graduate</span></div>
                <div id="units">{% if class_instance.cl.units %} {{class_instance.cl.units}} Units {% endif %}</div>
            </div>
        </div>
        <div class="card-segment">
            <h2 class="card-segment-head">
                Links   
            </h2>
            <div class="card-segment-body">
                <div class="card-button-list">
                    <ul id="class-links">
                        {% if class_instance.canvas %}
                        <li class="gradient"><a href="{{ class_instance.canvas }}">Canvas Site ></a></li>
                        {% endif %}
                        {% if class_instance.dept_site %}
                        <li class="gradient"><a href="{{ class_instance.dept_site }}">Department Page ></a></li>
                        {% endif %}
                        {% if class_instance.syllabus %}
                        <li class="gradient"><a href="{{class_instance.syllabus.url}}">Syllabus ></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div>
    </div>
    </div><div class="sidebyside card hawt">
        <div class="card-segment">
            <h2 class="card-segment-head">
                Methods
            </h2>
            <hr>
            <div class="card-segment-body">
                {% if class_instance.skills %}
                    {% for s in class_instance.skills.all %}
                        {{ s.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="card-segment">
            <h2 class="card-segment-head">
                Tools
            </h2>
            <hr>
            <div class="card-segment-body">
                {% if class_instance.software %}
                    {% for s in class_instance.software.all %}
                        {{ s.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% if class_instance.desc %}
<div class="long-content">
    {{ class_instance.desc|safe_markdown }}
    <hr>
</div>
{% endif %}
{% endif %}
{% endblock %}

classes/templates/classes/class_instance_list.html
{% extends "main/base.html" %}
{% load martortags %}
{% load static %}

{% block content %}

<div class="feature-text"><p>Current Teaching</p></div>
{% if current_upcoming %}
{% regroup current_upcoming by get_role_display as role_list %}
{% for role, role_classes in role_list %}
<div class="feature-text sub">{{role}}</div>
<div class="card-array">
    {% for c in role_classes %}<div class="card {% if c.cancel %}cancel{% endif %}">
    <div class="card-segment">
        {% if c.banner %}
            <a href="{% url 'classes:class_instance' c.slug %}"><div class="card-img"><div style="background-image:url({{c.banner.url}})"></div></div></a>
        {% endif %}
        <h4 class="supertitle">{{c.semester.get_semester_display}} {{c.semester.year}} | {% if c.dept_site %}<a href="{{ c.dept_site }}">{{c.cl.institution.short}}</a>{% else %}{{c.cl.institution.short}}{% endif %}</h4>
        <h2 class="card-segment-head"><a href="{% url 'classes:class_instance' c.slug %}">{{c.cl.title}}</a></h2>
        <hr>
        {% for i in c.instructors.all %}
            <h4><a href="{% url 'people:person' i.slug %}">{{ i.full_name }} ({{i.get_pronouns_display}})</a></h4>
        {% endfor %}
        {% if c.desc %}
            {{ c.desc|safe_markdown|truncatewords:15 }}
        {% endif %}
        <div class="card-button-list">
            <ul>
                {% if c.canvas %}
                    <li class="gradient"><a href="{{c.canvas}}">Canvas ></a></li>
                {% endif %}
                {% if c.syllabus %}
                    <li class="gradient"><a href="{{ c.syllabus }}">Syllabus ></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    </div>{% endfor %}
</div>{% endfor %}
{% else %}
<div class="long-content">
    No matching tutorials.
</div>
{% endif %}
{% if class_list %}
<div class="feature-text"><p>Previous Classes</p></div>
{% include page_template %}
{% endif %}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js'%}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 200
        });
    </script>
{% endblock %}

classes/templates/classes/class_instance_list_page.html
{% load el_pagination_tags %}
{% load martortags %}

{% paginate class_list %}
{% regroup class_list by get_role_display as role_list %}
{% for role, role_classes in role_list %}
<div class="feature-text sub">{{role}}</div>
<div class="card-array"> 

    {% for c in role_classes %}<div class="card {% if c.cancel %}cancel{% endif %}">
    <div class="card-segment">
    {% if c.banner %}
        <a href="{% url 'classes:class_instance' c.slug %}"><div class="card-img"><div style="background-image:url({{c.banner.url}})"></div></div></a>
    {% endif %}
    <h4 class="supertitle">{{c.semester.get_semester_display}} {{c.semester.year}} | {% if c.dept_site %}<a href="{{ c.dept_site }}">{{c.cl.institution.short}}</a>{% else %}{{c.cl.institution.short}}{% endif %}</h4>
    <h2 class="card-segment-head"><a href="{% url 'classes:class_instance' c.slug %}">{{c.cl.title}}</a></h2>
    <hr>
    {% for i in c.instructors.all %}
        <h4><a href="{{i.link}}">{{ i.full_name }} ({{i.get_pronouns_display}})</a></h4>
    {% endfor %}
    {% if c.desc %}
        {{ c.desc|safe_markdown|truncatewords:15 }}
    {% endif %}
    <div class="card-button-list">
        <ul>
            {% if c.canvas %}
                <li class="gradient"><a href="{{c.canvas}}">Canvas ></a></li>
            {% endif %}
            {% if c.syllabus %}
                <li class="gradient"><a href="{{ c.syllabus }}">Syllabus ></a></li>
            {% endif %}
        </ul>
    </div>
</div>
</div>{% endfor %}
</div>{% endfor %}
{% show_more %}